### PR TITLE
Change namespace to enduro

### PR DESCRIPTION
**Pull request by scollazo**

### CODE REVIEW

**Comment by djjuhasz** [comment]
@scollazo can you please provide some context for why you are changing the namespace to enduro?  What problem does this solve?

**Comment by scollazo** [comment]
We currently have a k3s cluster for development/test purposes, but the namespace "sdps" is already in use there by other (internal) project, so I want to be able to deploy this project in the same cluster, but avoid the namespace clash.

**Comment by djjuhasz** [comment]
@scollazo looks fine to me.  @sevein do you have any concerns with changing the namespace? I don't know any of the history of why sdps was used.

**Comment by sevein** [comment]
I don't mind the change! One alternative could be "enduro-sdps" so we can leave "enduro" reserved for https://github.com/artefactual-labs/enduro.

**Comment by djjuhasz** [comment]
I like "enduro-sdps".  What do you think @scollazo?

**Comment by scollazo** [comment]
Anything different from "sdps" works for me.

**Review by sevein — APPROVED** [review]
:+1:

**Pull request merged**
