### PR TITLE
Update frontend project structure according to create-vue

### PR DESCRIPTION
**Pull request by sevein**
This pull request introduces some changes to our frontend to align with some structural changes introduced by the create-vue template on new projects. I believe this effort helps bring our project closer to the community standards, easing its maintenace over time. 

- Multiple tsconfig files using [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) and the base config file sin [vuejs/tsconfig](https://github.com/vuejs/tsconfig). This seems to bring some performance improvements and simplicity.
- Move tests to `__tests__` directories under `src/`.

I've also updated some important dependencies:

- Upgrade to [Vite 5.0](https://vitejs.dev/blog/announcing-vite5)
- Upgrade to [Vitest 1.0](https://github.com/vitest-dev/vitest/releases/tag/v1.0.0)
- Upgrade to [TypeScript 5.3](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/)

Some tests required fixes. `vue3-promise-dialog` stopped working in the TS upgrade, `dashboard/typed-misc.d.ts` is a temporary solution.

**I haven't tested from the browser yet!**

### CODE REVIEW

**Comment by djjuhasz** [comment]
I checked out this branch, then restarted the Tilt container and got a bunch of errors:
```
[CMD 1/1] sh -c npm set cache /app/.npm && npm install-clean
9:01:33 PM [vite] changed tsconfig file detected: /app/tsconfig.json - Clearing cache and forcing full-reload to ensure TypeScript is compiled with updated config values.
9:01:33 PM [vite] vite.config.ts changed, restarting server...
9:01:34 PM [vite] server restarted.
failed to resolve "extends":"@tsconfig/node20/tsconfig.json" in /app/tsconfig.node.json
[sass] Can't find stylesheet to import.
  ╷
4 │ @import "helpers/focus-ring";
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/bootstrap/scss/_helpers.scss 4:9  @import
  src/styles/bootstrap.scss 10:9                 @import
  src/styles/main.scss 2:9                       root stylesheet
✘ [ERROR] Could not read from file: /app/node_modules/oidc-client-ts/dist/esm/oidc-client-ts.js

✘ [ERROR] Could not read from file: /app/node_modules/@pinia/plugin-debounce/dist/index.mjs

✘ [ERROR] Could not read from file: /app/node_modules/pinia/dist/pinia.mjs

✘ [ERROR] Could not read from file: /app/node_modules/unplugin-vue-router/dist/runtime.mjs

✘ [ERROR] Could not read from file: /app/node_modules/vue-router/dist/vue-router.mjs

✘ [ERROR] Could not read from file: /app/node_modules/bootstrap/js/dist/collapse.js

✘ [ERROR] Could not read from file: /app/node_modules/ts-debounce/dist/src/index.esm.js

✘ [ERROR] Could not read from file: /app/node_modules/vue3-promise-dialog/dist/vue3-promise-dialog.es.js

✘ [ERROR] Could not read from file: /app/node_modules/humanize-duration/humanize-duration.js

✘ [ERROR] Could not read from file: /app/node_modules/lodash-es/lodash.js

✘ [ERROR] Could not read from file: /app/node_modules/vue/dist/vue.runtime.esm-bundler.js

✘ [ERROR] Could not read from file: /app/node_modules/bootstrap/js/dist/offcanvas.js

✘ [ERROR] Could not read from file: /app/node_modules/moment/dist/moment.js

9:01:36 PM [vite] error while updating dependencies:
Error: Build failed with 13 errors:
error: Could not read from file: /app/node_modules/oidc-client-ts/dist/esm/oidc-client-ts.js
error: Could not read from file: /app/node_modules/@pinia/plugin-debounce/dist/index.mjs
error: Could not read from file: /app/node_modules/pinia/dist/pinia.mjs
error: Could not read from file: /app/node_modules/unplugin-vue-router/dist/runtime.mjs
error: Could not read from file: /app/node_modules/vue-router/dist/vue-router.mjs
...
    at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1649:15)
    at /app/node_modules/esbuild/lib/main.js:1058:25
    at /app/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
9:01:36 PM [vite] Internal server error: [sass] Can't find stylesheet to import.
  ╷
1 │ @import "bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/styles/bootstrap-base.scss 1:9  @import
  src/styles/main.scss 1:9            root stylesheet
  Plugin: vite:css
  File: /app/src/styles/bootstrap-base.scss:1:9
  Error: Can't find stylesheet to import.
    ╷
  1 │ @import "bootstrap/scss/functions";
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src/styles/bootstrap-base.scss 1:9  @import
    src/styles/main.scss 1:9            root stylesheet
      at Object.wrapException (/app/node_modules/sass/sass.dart.js:1252:43)
      at /app/node_modules/sass/sass.dart.js:81805:25
      at _wrapJsFunctionForAsync_closure.$protected (/app/node_modules/sass/sass.dart.js:4022:15)
      at _wrapJsFunctionForAsync_closure.call$2 (/app/node_modules/sass/sass.dart.js:33914:12)
      at _awaitOnObject_closure.call$1 (/app/node_modules/sass/sass.dart.js:33902:32)
      at Object._rootRunUnary (/app/node_modules/sass/sass.dart.js:4408:18)
      at StaticClosure.<anonymous> (/app/node_modules/sass/sass.dart.js:115526:16)
      at _CustomZone.runUnary$2$2 (/app/node_modules/sass/sass.dart.js:35338:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (/app/node_modules/sass/sass.dart.js:34401:51)
      at Object._Future__propagateToListeners (/app/node_modules/sass/sass.dart.js:4201:93)

added 642 packages, and audited 643 packages in 13s

160 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
  → Container enduro-dashboard-cc965cd8f-fk5fb/enduro-dashboard updated!
█
```

**Comment by djjuhasz** [comment]
Screenshot
image

**Comment by djjuhasz** [comment]
Hmm, looks like it might have been a cache problem, I restarted the container a few more times and everything seems to be working now.  There is an "EPIPE" error occurring periodically, but that was happening on main too. 

```
STEP 1/4 — Force update
     Beginning force update
     Deleting kubernetes objects:
     → Deployment/enduro-dashboard
     → Service/enduro-dashboard

STEP 2/4 — Building Dockerfile: [enduro-dashboard:dev]
Building Dockerfile for platform linux/amd64:
  # syntax = docker/dockerfile:1.4
  
  FROM node:20 AS builder
  WORKDIR /app
  COPY --link package.json package-lock.json ./
  RUN --mount=type=cache,target=/app/.npm \
      npm set cache /app/.npm && npm install-clean
  COPY --link . .
  RUN npm run build
  CMD npm run dev
  
  FROM nginx:alpine
  RUN apk add --no-cache bash
  
  ARG VERSION_PATH
  ARG VERSION_LONG
  ARG VERSION_SHORT
  ARG VERSION_GIT_HASH
  
  ENV ENDURO_DASHBOARD_DIST=/dist
  WORKDIR $ENDURO_DASHBOARD_DIST
  COPY --from=builder --link /app/dist .
  
  COPY <<EOF /etc/nginx/templates/default.conf.template
  upstream backend {
      least_conn;
      server \${ENDURO_API_ADDRESS};
  }
  server {
      listen 80;
      root /usr/share/nginx/html;
      absolute_redirect off;
      location /api/package/monitor {
          proxy_pass http://backend/package/monitor;
          proxy_http_version 1.1;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Upgrade \$http_upgrade;
          proxy_set_header Host \$host;
      }
      location /api/ {
          proxy_pass http://backend/;
          proxy_redirect / /api/;
      }
      location / {
          try_files \$uri \$uri/ /index.html;
      }
  }
  EOF
  
  # Run inject-vite-envs.sh on Nginx start
  ENV ENDURO_DASHBOARD_ROOT=/usr/share/nginx/html
  COPY --link ./hack/inject-vite-envs.sh /docker-entrypoint.d/50-inject-vite-envs.sh
  RUN echo "echo Starting enduro-dashboard version=${VERSION_LONG}" > /docker-entrypoint.d/55-stamping.sh
  RUN chmod +x /docker-entrypoint.d/50-inject-vite-envs.sh /docker-entrypoint.d/55-stamping.sh


     Building image
Beginning garbage collecting Kubernetes objects
Deleting kubernetes objects:
→ Service/enduro-dashboard
→ Deployment/enduro-dashboard
     resolve image config for docker.io/docker/dockerfile:1.4 [done: 371ms]
     docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
     [background] read source files 843.43kB [done: 100ms]
     [builder 1/6] FROM docker.io/library/node:20@sha256:445acd9b2ef7e9de665424053bf95652e0b8995ef36500557d48faf29300170a
     [builder 2/6] WORKDIR /app [cached]
     [builder 3/6] COPY --link package.json package-lock.json ./ [done: 82ms]
     [builder 4/6] RUN --mount=type=cache,target=/app/.npm     npm set cache /app/.npm && npm install-clean
       → 
       → added 642 packages, and audited 643 packages in 10s
       → 
       → 160 packages are looking for funding
       →   run `npm fund` for details
       → 
       → found 0 vulnerabilities
       → npm notice 
       → npm notice New patch version of npm available! 10.2.3 -> 10.2.4
       → npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v10.2.4>](https://github.com/npm/cli/releases/tag/v10.2.4%3E)
       → npm notice Run `npm install -g npm@10.2.4` to update!
       → npm notice 
     [builder 4/6] RUN --mount=type=cache,target=/app/.npm     npm set cache /app/.npm && npm install-clean [done: 14.847s]
     [builder 5/6] COPY --link . . [done: 124ms]
     [builder 6/6] RUN npm run build
       → 
       → > dashboard@0.0.0 build
       → > run-p type-check "build-only {@}" --
       → 
       → 
       → > dashboard@0.0.0 type-check
       → > vue-tsc --noEmit -p tsconfig.vitest.json --composite false
       → 
       → 
       → > dashboard@0.0.0 build-only
       → > vite build
       → 
       → vite v5.0.5 building for production...
       → transforming...
       → ✓ 911 modules transformed.
       → rendering chunks...
       → computing gzip size...
       → dist/index.html                                                                 0.43 kB │ gzip:   0.28 kB
       → dist/assets/details-line__raw_font-size_20px-fi4UQHon.css                       0.06 kB │ gzip:   0.07 kB
       → dist/assets/index-3R827mGh.css                                                  0.14 kB │ gzip:   0.13 kB
       → dist/assets/index-N7WmTVJC.css                                                  0.17 kB │ gzip:   0.11 kB
       → dist/assets/index-gK1PPwbH.css                                                160.48 kB │ gzip:  22.66 kB
       → dist/assets/index-sIVamYvN.js                                                   0.16 kB │ gzip:   0.15 kB
       → dist/assets/packages-bGAXOp1Y.js                                                0.17 kB │ gzip:   0.16 kB
       → dist/assets/locations-Tx7Af0lL.js                                               0.17 kB │ gzip:   0.16 kB
       → dist/assets/user-snIIGpFk.js                                                    0.17 kB │ gzip:   0.16 kB
       → dist/assets/signin-callback-jk3OBB7y.js                                         0.23 kB │ gzip:   0.20 kB
       → dist/assets/_...path_-OBYZiyFR.js                                               0.53 kB │ gzip:   0.37 kB
       → dist/assets/storage-lQkQvGHD.js                                                 0.57 kB │ gzip:   0.34 kB
       → dist/assets/StatusBadge.vue_vue_type_script_setup_true_lang-BdAa6cv5.js         0.63 kB │ gzip:   0.40 kB
       → dist/assets/bundle-line-7LmIhguR.js                                             0.66 kB │ gzip:   0.45 kB
       → dist/assets/rack-server-line-Tl_jQ76Q.js                                        1.04 kB │ gzip:   0.41 kB
       → dist/assets/signin-TzzQi7_T.js                                                  1.07 kB │ gzip:   0.62 kB
       → dist/assets/packages-CnkcYpo2.js                                                1.07 kB │ gzip:   0.57 kB
       → dist/assets/index-LUtRElvf.js                                                   1.12 kB │ gzip:   0.54 kB
       → dist/assets/PageLoadingAlert.vue_vue_type_script_setup_true_lang-9HAkc9LO.js    1.21 kB │ gzip:   0.66 kB
       → dist/assets/_id_-724Prr4X.js                                                    1.23 kB │ gzip:   0.71 kB
       → dist/assets/details-line__raw_font-size_20px-ZCUBeIiC.js                        1.35 kB │ gzip:   0.70 kB
       → dist/assets/_id_-T4Fjzj9o.js                                                    1.56 kB │ gzip:   0.93 kB
       → dist/assets/index-OeiTNPIl.js                                                   1.71 kB │ gzip:   0.85 kB
       → dist/assets/index-IX-LqHjl.js                                                   4.12 kB │ gzip:   1.95 kB
       → dist/assets/index-MTD6o_96.js                                                   4.63 kB │ gzip:   2.15 kB
       → dist/assets/index-secT5dOp.js                                                  16.43 kB │ gzip:   5.82 kB
       → dist/assets/UUID.vue_vue_type_script_setup_true_lang-PY-LIiZS.js               35.77 kB │ gzip:  12.78 kB
       → dist/assets/index-t2rt6ATg.js                                                 323.24 kB │ gzip: 104.98 kB
       → ✓ built in 8.20s
       → npm notice 
       → npm notice New patch version of npm available! 10.2.3 -> 10.2.4
       → npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v10.2.4>](https://github.com/npm/cli/releases/tag/v10.2.4%3E)
       → npm notice Run `npm install -g npm@10.2.4` to update!
       → npm notice 
     [builder 6/6] RUN npm run build [done: 11.06s]
     exporting to image [done: 13.935s]


STEP 3/4 — Pushing localhost:42237/enduro-dashboard:tilt-882c7884805e5240
     Pushing with Docker client
     Authenticating to image repo: localhost:42237
     Sending image data
     d78b22bc37a6: Layer already exists 
     e471edff4937: Layer already exists 
     b45af42c4137: Pushed 
     ca27f0baa64a: Pushed 
     db742d6deef4: Pushed 
     7973049f41b5: Layer already exists 
     f48a36f74def: Layer already exists 
     652b81616682: Layer already exists 
     80bd043d4663: Layer already exists 
     30f5cd833236: Layer already exists 
     7c32e0608151: Layer already exists 
     25a9e8449e71: Pushed 
     7cea17427f83: Layer already exists 

STEP 4/4 — Deploying
     Applying YAML to cluster
     Objects applied to cluster:
       → enduro-dashboard:service
       → enduro-dashboard:deployment

     Step 1 - 0.08s (Force update)
     Step 2 - 42.28s (Building Dockerfile: [enduro-dashboard:dev])
     Step 3 - 66.00s (Pushing localhost:42237/enduro-dashboard:tilt-882c7884805e5240)
     Step 4 - 0.05s (Deploying)
     DONE IN: 108.41s 


Tracking new pod rollout (enduro-dashboard-5976d7dbdd-94rrf):
     ┊ Scheduled       - <1s
     ┊ Initialized     - <1s
     ┊ Ready           - 12s
[event: pod enduro-sdps/enduro-dashboard-5976d7dbdd-94rrf] Pulling image "sdps-registry:5000/enduro-dashboard:tilt-882c7884805e5240"
[event: pod enduro-sdps/enduro-dashboard-5976d7dbdd-94rrf] Successfully pulled image "sdps-registry:5000/enduro-dashboard:tilt-882c7884805e5240" in 10.711247563s (10.71126429s including waiting)

> dashboard@0.0.0 dev
> vite


  VITE v5.0.5  ready in 660 ms

  ➜  Local:   [http://localhost:80/](http://localhost/)
  ➜  Network: use --host to expose
9:11:02 PM [vite] ✨ new dependencies optimized: @vueuse/core, bootstrap/js/dist/tooltip, @vue/reactivity
9:11:02 PM [vite] ✨ optimized dependencies changed. reloading
9:11:48 PM [vite] ws proxy socket error:
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:952:11)
    at Socket._write (node:net:964:8)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at Writable.write (node:internal/streams/writable:494:10)
    at Socket.ondata (node:internal/streams/readable:985:22)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
```

**Comment by djjuhasz** [comment]
Screenshot:
image

**Comment by sevein** [comment]
Thank you! :heart_eyes:

**Pull request merged**
