### PR TITLE
dev/fix indenting lint rules

### PR DESCRIPTION
**Pull request by Diogenesoftoronto**
- remove checklist
- use subheaders instead
- fix lint error
- Update docs/src/dev-manual/archivematica.md
- fix spacing, case
- fix spacing, case
- fix indenting, breaks markdownlint
- remove hardtabs
- make consistent use of ``
- Update docs/src/dev-manual/archivematica.md
- make consistent use of ``
- Fix markdownlint rules to format indenting

### CODE REVIEW

**Comment by sevein** [comment]
@Diogenesoftoronto, does this PR replace #839?

**Comment by Diogenesoftoronto** [comment]
> @Diogenesoftoronto, does this PR replace #839?

No I just switched on the wrong branch should have only changes from main with the last commit

**Comment by sevein** [comment]
Hmmm I don't get it, they look similar.

**Comment by sevein** [comment]
Fixed in b32ea8b75c377d50c0cf996a75d885f45198d40d.

**Pull request closed without merging**
